### ISSUE TITLE
Impossible to search

### ISSUE THREAD

**Issue by eiffel-fl** [inspektor-gadget/website#71] opened 2024-08-19 07:08 UTC
Hi.

I already [met this bug](https://github.com/inspektor-gadget/website/pull/53#pullrequestreview-2212677211) and it is still present today.

Best regards.

**Comment by mauriciovasquezbernal** [comment] 2024-08-21 15:34
Isn't it a duplicate of #61?

**Closed as completed** 2024-08-22 07:29 UTC
